
metadata:
  option_name: ""
  architecture_name: "clam"

loader_kwargs:
  train: { 'batch_size' : 8, 'nr_procs' : 4}
  infer: { 'batch_size' : 8, 'nr_procs' : 4}

model_kwargs:
  dims: [2048, 512, 256]
  top_k_samples: 8
  num_types: 2

optimizer_kwargs:
  betas:
  - 0.9
  - 0.999
  lr: 1.0e-04
  weight_decay: 0.0
seed: 5
